# Generated by Django 5.2.17 on 2026-08-10 14:58

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='分支名')),
            ],
        ),
        migrations.CreateModel(
            name='ExecutionRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exec_date', models.DateField()),
                ('build_start_at', models.DateTimeField(blank=True, null=True)),
                ('build_end_at', models.DateTimeField(blank=True, null=True)),
                ('smoke_start_at', models.DateTimeField(blank=True, null=True)),
                ('smoke_end_at', models.DateTimeField(blank=True, null=True)),
                ('analysis_start_at', models.DateTimeField(blank=True, null=True)),
                ('analysis_end_at', models.DateTimeField(blank=True, null=True)),
                ('push_start_at', models.DateTimeField(blank=True, null=True)),
                ('push_end_at', models.DateTimeField(blank=True, null=True)),
                ('conclusion', models.CharField(blank=True, max_length=20, null=True, verbose_name='结论')),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('push_status', models.CharField(blank=True, max_length=20, null=True, verbose_name='推送状态')),
                ('release_approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SecurityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default='', max_length=100)),
                ('action', models.CharField(max_length=100)),
                ('detail', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StrategyTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='模板名')),
                ('smoke_minutes', models.PositiveIntegerField(default=0)),
                ('analysis_minutes', models.PositiveIntegerField(default=0)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', '管理员'), ('pm', '版本负责人'), ('builder', '构建人员'), ('tester', '测试人员'), ('integrator', '集成人员')], default='builder', max_length=20, verbose_name='角色')),
                ('display_name', models.CharField(blank=True, default='', max_length=100, verbose_name='显示名')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AdminOpLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('target_type', models.CharField(blank=True, default='', max_length=50)),
                ('target_id', models.CharField(blank=True, default='', max_length=50)),
                ('detail', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='build_protection_service.executionround')),
            ],
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='策略名')),
                ('build_start_time', models.CharField(max_length=5, verbose_name='构建开始时间')),
                ('push_start_time', models.CharField(blank=True, max_length=5, null=True, verbose_name='推送开始时间')),
                ('push_mode', models.CharField(choices=[('normal', '正常流程推送'), ('sync', '同步推送冒烟')], default='normal', max_length=10, verbose_name='推送模式')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategies', to='build_protection_service.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_strategies', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='strategies', to='build_protection_service.strategytemplate')),
            ],
            options={
                'ordering': ['build_start_time'],
            },
        ),
        migrations.AddField(
            model_name='executionround',
            name='strategy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='build_protection_service.strategy'),
        ),
        migrations.CreateModel(
            name='StrategyChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_desc', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='build_protection_service.strategy')),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='版本号')),
                ('status', models.CharField(default='active', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pm_user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='bound_version', to=settings.AUTH_USER_MODEL, verbose_name='PM')),
            ],
        ),
        migrations.AddField(
            model_name='branch',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='build_protection_service.version'),
        ),
        migrations.AlterUniqueTogether(
            name='executionround',
            unique_together={('strategy', 'exec_date')},
        ),
        migrations.AlterUniqueTogether(
            name='branch',
            unique_together={('version', 'name')},
        ),
    ]
