# Generated by Django 5.2.17 on 2026-08-15 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('build_protection_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('conclusion', models.CharField(choices=[('pass', '通过'), ('fail', '不通过'), ('risk', '有风险')], max_length=20, verbose_name='结论')),
                ('environment', models.CharField(blank=True, default='', max_length=255, verbose_name='验证环境')),
                ('summary', models.TextField(verbose_name='验证内容')),
                ('risks', models.TextField(blank=True, default='', verbose_name='问题与风险')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布')], default='draft', max_length=20, verbose_name='状态')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('publish_count', models.PositiveIntegerField(default=0, verbose_name='发布次数')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_reports', to=settings.AUTH_USER_MODEL)),
                ('strategy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='build_protection_service.strategy')),
                ('version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='build_protection_service.version')),
            ],
        ),
        migrations.CreateModel(
            name='ReportPublishRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screenshot', models.TextField(verbose_name='页面截图 base64')),
                ('push_status', models.CharField(default='pushed', max_length=20, verbose_name='推送状态')),
                ('push_target', models.CharField(default='构建通知群', max_length=100, verbose_name='模拟接收人')),
                ('message', models.CharField(max_length=255, verbose_name='推送摘要')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_publishes', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publish_records', to='build_protection_service.verificationreport')),
            ],
        ),
    ]
