# Generated by Django 5.2.17 on 2026-08-16 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('build_protection_service', '0002_verificationreport_reportpublishrecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReportPublishRecord',
        ),
    ]
