# Generated by Django 5.2.17 on 2026-08-16 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('build_protection_service', '0003_delete_reportpublishrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationreport',
            name='deprecated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='废弃时间'),
        ),
        migrations.AddField(
            model_name='verificationreport',
            name='deprecated_reason',
            field=models.TextField(blank=True, default='', verbose_name='废弃原因'),
        ),
        migrations.AlterField(
            model_name='verificationreport',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('deprecated', '已废弃')], default='draft', max_length=20, verbose_name='状态'),
        ),
    ]
