# Generated by Django 5.2.17 on 2026-08-16 14:34

from django.db import migrations, models


def forwards_func(apps, schema_editor):
    """FK 数据搬移至文本快照：版本/策略/作者取名称；历史已废弃报告转为已发布。

    本函数在 AddField 之后、RemoveField 之前执行，因此可同时读取
    旧外键字段与新增文本字段。
    """
    VerificationReport = apps.get_model("build_protection_service", "VerificationReport")
    for report in VerificationReport.objects.all().iterator():
        report.version_name = report.version.name if report.version_id else ""
        report.strategy_name = report.strategy.name if report.strategy_id else ""
        report.created_by_username = (
            report.created_by.username if report.created_by_id else ""
        )
        if report.status == "deprecated":
            report.status = "published"
        report.save(
            update_fields=[
                "version_name",
                "strategy_name",
                "created_by_username",
                "status",
            ]
        )


class Migration(migrations.Migration):

    dependencies = [
        ('build_protection_service', '0004_verificationreport_deprecated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportRevisionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.IntegerField(verbose_name='报告ID')),
                ('report_title', models.CharField(blank=True, default='', max_length=200, verbose_name='报告标题')),
                ('action', models.CharField(choices=[('create', '创建'), ('update', '修改'), ('publish', '发布')], max_length=20, verbose_name='动作')),
                ('field_name', models.CharField(blank=True, default='', max_length=100, verbose_name='修改字段')),
                ('before_value', models.TextField(blank=True, default='', verbose_name='修改前内容')),
                ('after_value', models.TextField(blank=True, default='', verbose_name='修改后内容')),
                ('operator_username', models.CharField(max_length=100, verbose_name='操作人账号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
            ],
            options={
                'verbose_name': '报告修改记录',
                'verbose_name_plural': '报告修改记录',
                'ordering': ['-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='verificationreport',
            options={'ordering': ['-updated_at'], 'verbose_name': '验证报告', 'verbose_name_plural': '验证报告'},
        ),
        migrations.AddField(
            model_name='verificationreport',
            name='created_by_username',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='作者账号'),
        ),
        migrations.AddField(
            model_name='verificationreport',
            name='strategy_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='策略'),
        ),
        migrations.AddField(
            model_name='verificationreport',
            name='version_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='版本'),
        ),
        migrations.RunPython(forwards_func, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='verificationreport',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='verificationreport',
            name='deprecated_at',
        ),
        migrations.RemoveField(
            model_name='verificationreport',
            name='deprecated_reason',
        ),
        migrations.RemoveField(
            model_name='verificationreport',
            name='strategy',
        ),
        migrations.RemoveField(
            model_name='verificationreport',
            name='version',
        ),
        migrations.AlterField(
            model_name='verificationreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='verificationreport',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='verificationreport',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('published', '已发布')], default='draft', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='verificationreport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]