"""initialize all business tables

Revision ID: 7e17e630acb7
Revises: 
Create Date: 2026-08-09 23:37:38.207684

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '7e17e630acb7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('admin_op_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operator', sa.Integer(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('target_type', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['operator'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('security_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('event', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('ip', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('strategy_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('smoke_minutes', sa.Integer(), nullable=False),
    sa.Column('analysis_minutes', sa.Integer(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('pm_user_id', sa.Integer(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pm_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('pm_user_id')
    )
    op.create_table('branch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['version.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_id', 'name', name='uq_branch_version_name')
    )
    op.create_table('strategy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('build_start_time', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=False),
    sa.Column('push_mode', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branch.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['strategy_template.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('execution_round',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('exec_date', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('push_start', sa.DateTime(), nullable=True),
    sa.Column('push_end', sa.DateTime(), nullable=True),
    sa.Column('build_start', sa.DateTime(), nullable=False),
    sa.Column('build_end', sa.DateTime(), nullable=False),
    sa.Column('smoke_start', sa.DateTime(), nullable=False),
    sa.Column('smoke_end', sa.DateTime(), nullable=False),
    sa.Column('analysis_start', sa.DateTime(), nullable=False),
    sa.Column('analysis_end', sa.DateTime(), nullable=False),
    sa.Column('conclusion', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('conclusion_by', sa.Integer(), nullable=True),
    sa.Column('conclusion_at', sa.DateTime(), nullable=True),
    sa.Column('conclusion_note', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('push_status', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('release_approved', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['conclusion_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategy.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('strategy_id', 'exec_date', name='uq_round_strategy_date')
    )
    op.create_table('strategy_change_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('operator', sa.Integer(), nullable=False),
    sa.Column('field', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('old_value', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('new_value', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['operator'], ['user.id'], ),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('execution_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('stage', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('event', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['round_id'], ['execution_round.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('execution_log')
    op.drop_table('strategy_change_log')
    op.drop_table('execution_round')
    op.drop_table('strategy')
    op.drop_table('branch')
    op.drop_table('version')
    op.drop_table('strategy_template')
    op.drop_table('security_log')
    op.drop_table('admin_op_log')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
